name: Nightly GCP Backup

on:
  # Disabled by default; run manually when configured
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Backup workflow disabled by default. Configure secrets and backup script before enabling."


