name: Nightly GCP Backup

on:
  schedule:
    - cron: '0 8 * * *' # 08:00 UTC daily
  workflow_dispatch:

jobs:
  backup:
    # Only run when required secrets are configured to prevent red runs
    if: ${{ secrets.GCP_SA_KEY_JSON != '' && secrets.GOOGLE_CLOUD_PROJECT != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 460.0.0'
      - name: Run backup script
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
        run: bash scripts/firestore-backup.sh


