name: CI Minimal

on:
  push:
    branches: [ main, feat/** ]
  pull_request:

jobs:
  web-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - name: Use corepack PNPM from packageManager
        run: |
          corepack enable
          corepack prepare pnpm@$(node -p "require('./package.json').packageManager.split('@')[1]") --activate
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps (no frozen)
        run: pnpm install --no-frozen-lockfile
      - name: Build web
        working-directory: apps/web
        run: pnpm build

  app-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - name: Use corepack PNPM from packageManager
        run: |
          corepack enable
          corepack prepare pnpm@$(node -p "require('./package.json').packageManager.split('@')[1]") --activate
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Determine app directory
        id: appdir
        run: |
          if [ -f "typeb-family-app/package.json" ]; then
            echo "APP_DIR=typeb-family-app" >> $GITHUB_ENV
          else
            echo "APP_DIR=." >> $GITHUB_ENV
          fi
      - name: Skip if submodule not present
        if: ${{ env.APP_DIR == '.' }}
        run: echo "Mobile app submodule missing; skipping unit tests."
      - name: Install app deps
        if: ${{ env.APP_DIR != '.' }}
        working-directory: ${{ env.APP_DIR }}
        run: pnpm install --no-frozen-lockfile
      - name: Run unit tests
        if: ${{ env.APP_DIR != '.' }}
        working-directory: ${{ env.APP_DIR }}
        run: pnpm run test:unit --silent
