name: Firestore Rules Tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  rules-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm -w install --frozen-lockfile=false
      - name: Run rules tests (if present)
        run: pnpm -w run test:rules --if-present


