name: Firestore Rules Tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  rules-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use corepack PNPM from packageManager
        run: |
          corepack enable
          corepack prepare pnpm@$(node -p "require('./package.json').packageManager.split('@')[1]") --activate
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm -w install --frozen-lockfile=false
      - name: Run rules tests (if present)
        run: |
          if jq -e '.scripts["test:rules"]' package.json >/dev/null 2>&1; then
            pnpm -w run test:rules
          else
            echo "No test:rules script; skipping"
          fi


